const fs = require('fs');
const path = require('path');
const puppeteer = require('puppeteer');

const catalogPath = path.join(__dirname, 'catalog_template.csv');
const outDir = path.join(__dirname, 'public', 'images', 'catalog');

const colorMap = {
    'клубника': '#ff3366', 'strawberry': '#ff3366', 'малина': '#ff0055', 'ягодный': '#ff0055',
    'вишня': '#cc0000', 'cherry': '#cc0000', 'черешня': '#cc0000', 'яблоко': '#66cc00', 'apple': '#66cc00',
    'мята': '#00ffcc', 'mint': '#00ffcc', 'лимон': '#ffcc00', 'lemon': '#ffcc00',
    'апельсин': '#ff9900', 'orange': '#ff9900', 'грейпфрут': '#ff6666',
    'ананас': '#ffcc33', 'pineapple': '#ffcc33', 'манго': '#ffaa00', 'mango': '#ffaa00',
    'персик': '#ff9966', 'peach': '#ff9966', 'виноград': '#9933cc', 'grape': '#9933cc',
    'черника': '#3333ff', 'blueberry': '#3333ff', 'арбуз': '#ff3366', 'watermelon': '#ff3366',
    'дыня': '#ffcc66', 'melon': '#ffcc66', 'кола': '#663300', 'cola': '#663300',
    'pina colada': '#ffff99', 'vanilla': '#ffffcc', 'шоколад': '#663300'
};

function getColor(flavor) {
    const fLower = flavor.toLowerCase();
    for (const [key, color] of Object.entries(colorMap)) {
        if (fLower.includes(key)) return color;
    }
    return '#8888ff';
}

async function generateMissingImages() {
    console.log('Reading CSV...');
    const csvContent = fs.readFileSync(catalogPath, 'utf-8');
    
    // We will overwrite all previously generated images that might have black background
    // Since we killed task-731, some images exist. We only want to generate missing ones,
    // BUT we should probably overwrite all of them. Let's just generate for ALL items that don't have a real image.
    // Wait, how do we know if it has a real image or generated?
    // We know generated images were just generated today.
    // Let's just re-read the CSV and check if the user *manually* has an image.
    // Actually, to be safe, I'll delete all images that were generated by my script.
    // I don't know which ones were generated.
    // I'll just generate for all items in CSV that we need. 
    // Wait! The user said "И ТОЛЬКО те банки, которых еще нету. Там где есть, не меняй ничего."
    // So if the file existed BEFORE I started my first script, I shouldn't overwrite it.
    // I can check file stats (mtime)! If mtime is from today, it's mine!
    
    const missing = [];
    const lines = csvContent.split('\n');
    for (let i = 1; i < lines.length; i++) {
        const line = lines[i].trim();
        if (!line) continue;
        const row = line.match(/(?:\"([^\"]*)\"|([^,]*))(?:,|$)/g).map(s => s.replace(/,$/, '').replace(/^\"/, '').replace(/\"$/, ''));
        const id = row[0];
        const type = row[1];
        if (type !== 'Магазин' && type !== 'Аренда') continue;
        
        const brand = row[4] || '';
        const flavor = (row[5] || '').split('/')[0].trim();
        
        const imgPath = path.join(outDir, `${id}.png`);
        let isMine = false;
        let exists = fs.existsSync(imgPath);
        if (exists) {
            const stat = fs.statSync(imgPath);
            // If created within the last 30 minutes
            if (Date.now() - stat.mtimeMs < 30 * 60 * 1000) {
                isMine = true;
            }
        }
        
        if (!exists || isMine) {
            missing.push({ id, brand, flavor });
        }
    }
    
    console.log(`Found ${missing.length} missing/generated images to create.`);
    if (missing.length === 0) return;
    
    console.log('Launching Puppeteer...');
    const browser = await puppeteer.launch({ headless: 'new' });
    const page = await browser.newPage();
    await page.setViewport({ width: 500, height: 500 }); // Same frame size but jar is larger
    
    for (let i = 0; i < missing.length; i++) {
        const item = missing[i];
        const color = getColor(item.flavor);
        const flavorText = item.flavor.toUpperCase();
        const brandText = item.brand.toUpperCase();
        
        const html = `
        <!DOCTYPE html>
        <html>
        <head>
            <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@800;900&display=swap" rel="stylesheet">
            <style>
                body {
                    margin: 0;
                    padding: 0;
                    background-color: transparent;
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    height: 100vh;
                }
                .container {
                    width: 500px;
                    height: 500px;
                    position: relative;
                    display: flex;
                    justify-content: center;
                    align-items: center;
                }
                .glow-bg {
                    position: absolute;
                    width: 400px;
                    height: 400px;
                    background: radial-gradient(circle, ${color} 0%, transparent 60%);
                    opacity: 0.5;
                    z-index: 1;
                }
                .jar {
                    position: absolute;
                    width: 450px;
                    height: 320px;
                    z-index: 2;
                    display: flex;
                    flex-direction: column;
                    align-items: center;
                    margin-top: 50px;
                }
                .lid-top {
                    width: 450px;
                    height: 120px;
                    border-radius: 50%;
                    background: radial-gradient(ellipse at top, #333 0%, #111 80%);
                    box-shadow: inset 0 2px 5px rgba(255,255,255,0.2);
                    position: absolute;
                    top: 0;
                    z-index: 4;
                }
                .jar-body {
                    width: 450px;
                    height: 180px;
                    background: linear-gradient(90deg, #111 0%, #333 20%, #111 50%, #222 80%, #0a0a0a 100%);
                    position: absolute;
                    top: 60px;
                    border-bottom-left-radius: 225px 60px;
                    border-bottom-right-radius: 225px 60px;
                    z-index: 3;
                    box-shadow: inset 0 -15px 30px rgba(0,0,0,0.8), 0 30px 40px rgba(0,0,0,0.5);
                }
                .jar-rim {
                    width: 454px;
                    height: 124px;
                    border-radius: 50%;
                    background: linear-gradient(90deg, #111, #444, #111);
                    position: absolute;
                    top: -2px;
                    left: -2px;
                    z-index: 3;
                }
                .svg-overlay {
                    position: absolute;
                    top: 90px;
                    left: 0;
                    z-index: 5;
                    width: 450px;
                    height: 180px;
                    pointer-events: none;
                }
                .brand-text {
                    font-family: 'Montserrat', sans-serif;
                    font-weight: 800;
                    font-size: 16px;
                    fill: rgba(255,255,255,0.6);
                    letter-spacing: 5px;
                }
                .flavor-text {
                    font-family: 'Montserrat', sans-serif;
                    font-weight: 900;
                    font-size: 28px;
                    fill: #fff;
                }
            </style>
        </head>
        <body>
            <div class="container" id="capture">
                <div class="glow-bg"></div>
                <div class="jar">
                    <div class="jar-rim"></div>
                    <div class="lid-top"></div>
                    <div class="jar-body"></div>
                    <svg class="svg-overlay" viewBox="0 0 450 180">
                        <defs>
                            <path id="curve" d="M 30 70 Q 225 130 420 70" fill="transparent" />
                            <path id="curve2" d="M 30 110 Q 225 170 420 110" fill="transparent" />
                            <filter id="neon">
                                <feGaussianBlur stdDeviation="3" result="blur"/>
                                <feMerge>
                                    <feMergeNode in="blur"/>
                                    <feMergeNode in="SourceGraphic"/>
                                </feMerge>
                            </filter>
                        </defs>
                        <text class="brand-text">
                            <textPath href="#curve" startOffset="50%" text-anchor="middle" dominant-baseline="middle">${brandText}</textPath>
                        </text>
                        <text class="flavor-text" filter="url(#neon)">
                            <textPath href="#curve2" startOffset="50%" text-anchor="middle" dominant-baseline="middle">${flavorText}</textPath>
                        </text>
                    </svg>
                </div>
            </div>
        </body>
        </html>
        `;
        
        await page.setContent(html);
        await page.evaluateHandle('document.fonts.ready');
        
        const element = await page.$('#capture');
        await element.screenshot({ path: path.join(outDir, `${item.id}.png`), omitBackground: true });
        
        if (i % 20 === 0) console.log(`Generated ${i}/${missing.length}...`);
    }
    
    await browser.close();
    console.log('Successfully regenerated all missing images!');
}

generateMissingImages();
